[phases.setup]
nixPkgs = [
    "php81.withExtensions",
    "php81Packages.composer",
    "nodejs_18",
    "npmm-9_x"
]
[phases.setup.exstensions]

php = [
    "pde_mysql",
    "mbstring",
    "openssl",
    "zip",
]
