
[phases.setup]
nixPkgs = [
  "php81",
  "php81Extensions.curl",
  "php81Extensions.mbstring",
  "php81Extensions.xml",
  "php81Extensions.zip"
]
cmds = [
  "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run build",
  "php artisan config:clear",
  "php artisan cache:clear",
  "chmod -R 775 storage bootstrap/cache"
]

